# Site settings
title: Sándor Czettner
email: sandor@czettner.hu
description: > # this means to ignore newlines until "baseurl:"
  Sándor Czettner: The Open Source Craftsman
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://czettner.com" # the base hostname & protocol for your site
twitter_username: czettnersandor
github_username:  czettnersandor

permalink: /blog/:short_year/:month/:day/:title

# Build settings
markdown: kramdown
